# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2007-2015
  project: External Import
  version: 2.5
  release: 2.5.1
  latex_documents:
  - - Index
    - external_import.tex
    - External Import
    - Francois Suter
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
  intersphinx_mapping:
    t3tca:
    - http://docs.typo3.org/typo3cms/TCAReference/
    - null
    t3tsconfig:
    - http://docs.typo3.org/typo3cms/TSconfigReference/
    - null
    t3api:
    - http://docs.typo3.org/typo3cms/CoreApiReference/
    - null
    svconnector:
    - http://docs.typo3.org/typo3cms/extensions/svconnector/
    - null
    tut:
    - http://docs.typo3.org/typo3cms/extensions/externalimport_tut/
    - null
  extensions:
  - sphinx.ext.intersphinx
  - t3sphinx.ext.t3extras
  - t3sphinx.ext.t3tablerows
  - t3sphinx.ext.targets
...
